### ISSUE TITLE
Modificar imagem da página inicial

### ISSUE THREAD

**Issue by zampolo** [LAPSHub/homepage#4]

**Comment by zampolo** [comment]
Não seria o "carrossel" com as imagens que enviamos?

**Comment by Leonardo-Soares** [comment]
Seria sim estarei fazendo a alteração

**Comment by Leonardo-Soares** [comment]
commit do carrosel https://github.com/LAPSHub/homepage/commit/eb3bbc067c7f71dc50638975f4ef7ae99d4c66f1

**Comment by zampolo** [comment]
Oi, Leonardo.
Ficou bom. 
Fecharei a issue.
